# Generated by Django 3.1 on 2020-08-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
